name: Deploy Backend to Azure App Service
on:
  # Trigger on push to main branch in backend folder
  push:
    branches: [ main ]
    paths:
      - 'backend/**'

  # Allow manual run from GitHub UI
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install & Build
        run: |
          cd backend
          npm ci
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME_BACKEND }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_BACKEND }}
          package: ./backend
